type = "javascript"
name = "api"
workers_dev = true

account_id = ""
usage_model = ""
route = ""
zone_id = ""

kv_namespaces = []

compatibility_date = "2021-12-19"

[build.upload]
format = "modules"
dir = "./out"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
ALLOWED_ORIGIN = "http://localhost:3000"

[env.staging.vars]
ALLOWED_ORIGIN = "https://refresh.inklingtest.com"

[env.production.vars]
ALLOWED_ORIGIN = "https://refresh.fiveclawd.com"
