name = "api"
type = "javascript"
workers_dev = true

account_id = "<snip>"

compatibility_date = "2021-12-19"

kv-namespaces = [
  { binding = "REFRESH_KV", id = "<snip>", preview_id = "<snip>" }
]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "./out"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.development]
kv-namespaces = [
  { binding = "REFRESH_KV", id = "<snip>", preview_id = "<snip>" }
]

[env.development.vars]
ALLOWED_ORIGIN = "<snip>"
AUDIENCE = "<snip>"
JWKS_URL = "<snip>"
WORKS_DISCORD_URL = "<snip>"
WEEKS_DISCORD_URL = "<snip>"
AWS_ACCESS_KEY_ID = "<snip>"
AWS_SECRET_ACCESS_KEY = "<snip>"
AWS_DEFAULT_REGION = "<snip>"
AWS_S3_BUCKET = "<snip>"
TWIC_URL = "<snip>"
CDN_HOSTNAME = "<snip>"
SENTRY_DSN = "<snip>"
ENVIRONMENT = "development"

[env.staging]
kv-namespaces = [
  { binding = "REFRESH_KV", id = "<snip>", preview_id = "<snip>" }
]

[env.staging.vars]
ALLOWED_ORIGIN = "<snip>"
AUDIENCE = "<snip>"
JWKS_URL = "<snip>"
WORKS_DISCORD_URL = "<snip>"
WEEKS_DISCORD_URL = "<snip>"
AWS_ACCESS_KEY_ID = "<snip>"
AWS_SECRET_ACCESS_KEY = "<snip>"
AWS_DEFAULT_REGION = "<snip>"
AWS_S3_BUCKET = "<snip>"
TWIC_URL = "<snip>"
CDN_HOSTNAME = "<snip>"
SENTRY_DSN = "<snip>"
ENVIRONMENT = "staging"

[env.production]
kv-namespaces = [
  { binding = "REFRESH_KV", id = "<snip>", preview_id = "<snip>" }
]

[env.production.vars]
ALLOWED_ORIGIN = "<snip>"
AUDIENCE = "<snip>"
JWKS_URL = "<snip>"
WORKS_DISCORD_URL = "<snip>"
WEEKS_DISCORD_URL = "<snip>"
AWS_ACCESS_KEY_ID = "<snip>"
AWS_SECRET_ACCESS_KEY = "<snip>"
AWS_DEFAULT_REGION = "<snip>"
AWS_S3_BUCKET = "<snip>"
TWIC_URL = "<snip>"
CDN_HOSTNAME = "<snip>"
SENTRY_DSN = "<snip>"
ENVIRONMENT = "production"
