type = "javascript"
name = "api"
workers_dev = true

account_id = ""
usage_model = ""
route = ""
zone_id = ""

kv_namespaces = []

compatibility_date = "2021-12-19"

[build.upload]
format = "modules"
dir = "./out"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
ALLOWED_ORIGIN = "http://localhost:3000"
AUDIENCE = "http://localhost:8787/api/"
JWKS_URL = "https://refresh-dev.au.auth0.com"
WEEKS_DISCORD_URL = "https://discord.com/api/webhooks/..."
WORKS_DISCORD_URL = "https://discord.com/api/webhooks/..."
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_DEFAULT_REGION = ""
AWS_S3_BUCKET = ""
TWIC_URL = ""
CDN_HOSTNAME = "refresh-cdn.fiveclawd.com"

[env.staging.vars]
ALLOWED_ORIGIN = "https://refresh.inklingtest.com"
AUDIENCE = "https://refresh.inklingtest.com/api/"
JWKS_URL = "https://refresh-uat.au.auth0.com"
WEEKS_DISCORD_URL = "https://discord.com/api/webhooks/..."
WORKS_DISCORD_URL = "https://discord.com/api/webhooks/..."
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_DEFAULT_REGION = ""
AWS_S3_BUCKET = ""
TWIC_URL = ""
CDN_HOSTNAME = "refresh-cdn.fiveclawd.com"

[env.production.vars]
ALLOWED_ORIGIN = "https://refresh.fiveclawd.com"
AUDIENCE = "https://refresh.fiveclawd.com/api/"
JWKS_URL = "https://refresh.au.auth0.com"
WEEKS_DISCORD_URL = "https://discord.com/api/webhooks/..."
WORKS_DISCORD_URL = "https://discord.com/api/webhooks/..."
AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_DEFAULT_REGION = ""
AWS_S3_BUCKET = ""
TWIC_URL = ""
CDN_HOSTNAME = "refresh-cdn.fiveclawd.com"
